# Site settings
title           : Shape Framework Documentation
email           : jmatc1@gmail.com
description     : "Shape Framework Documentation"
baseurl         : ""
url             : "https://github.com/jmatc"
twitter_username: jmatc
github_username : jmatc

# Build settings
destination     : _public
exclude         : [
  'grunt',
  'node_modules',
  'bower_components',
  'Gruntfile.js',
  'package.json',
  'bower.json',
  'assets/stylesheets/*.scss'
]
highlighter     : true
markdown        : rdiscount
permalink       : /:title
port            : 1234